# Generated by Django 4.2.6 on 2023-10-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='restaurant_id',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='posts.restaurant'),
        ),
    ]
