# Generated by Django 4.2.6 on 2023-10-13 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_remove_post_restaurant_id_post_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
