# Generated by Django 4.2.6 on 2023-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="search_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
