# Generated by Django 4.2.7 on 2023-11-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_restaurant_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
