# Generated by Django 4.2.7 on 2023-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sentiment',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
