# Generated by Django 4.2.6 on 2023-10-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ko_label", models.CharField(max_length=255)),
                ("en_label", models.CharField(max_length=255)),
            ],
        ),
    ]
