# Generated by Django 4.2.6 on 2023-10-24 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_delete_tag_user_tags"),
        ("posts", "0005_post_tags"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
    ]
