# Generated by Django 4.2.6 on 2023-10-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_rename_tags_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("country", "country"),
                    ("ingredient", "ingredient"),
                    ("atmosphere", "atmosphere"),
                ],
                default="country",
                max_length=20,
            ),
        ),
    ]
