# Generated by Django 4.2.6 on 2023-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0004_alter_tag_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("from_category", "from_category"),
                    ("user_stat", "user_stat"),
                    ("atmosphere", "atmosphere"),
                ],
                default="country",
                max_length=20,
            ),
        ),
    ]
