# Generated by Django 4.2.6 on 2023-10-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tag_user_avatar_url_user_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userTags',
        ),
    ]
