# Generated by Django 4.2.6 on 2023-10-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("users", "0003_remove_user_usertags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="tags.tags"
            ),
        ),
    ]
