# Generated by Django 4.2.6 on 2023-11-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_follower_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
